apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 of 'postgres'
  POSTGRES_PASSWORD: cG9zdGdyZXM=   # base64 of 'postgres'
  POSTGRES_DB: ZHJlYW12YWNhdGlvbnM= # base64 of 'dreamvacations'
